apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-credential-injector
  namespace: daaas-system
spec:
  project: platform
  destination:
    namespace: daaas-system
    name: in-cluster
  source:
    repoURL: https://github.com/StatCan/argocd-manifests.git
    path: daaas-system/minio-credential-injector
    targetRevision: null
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
