apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../applications/daaas-eck.yaml
- ../applications/minio-credential-injector.yaml

patchesJSON6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: '.*'
  patch: |-
    - op: replace
      path: /spec/source/targetRevision
      value: master
